version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: users_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users_db
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"